---
- name: Install Packetbeat
  hosts: hosts
  become: true
  vars:
    haproxy_ssl: false

  environment: "{{ deployment_environment_variables | default({}) }}"

  vars_files:
    - vars/variables.yml

  pre_tasks:
    - include_tasks: common_task_data_node_hosts.yml
      tags:
        - always

  tasks:
    - include_tasks: common_task_install_elk_repo.yml

    - name: Ensure packetbeat is installed
      apt:
        name: "{{ item }}"
        state: "{{ elk_package_state | default('present') }}"
        update_cache: true
      with_items:
        - tcpdump
        - packetbeat
      register: _apt_task
      until: _apt_task is success
      retries: 3
      delay: 2
      tags:
        - package_install

    - name: exit playbook after uninstall
      meta: end_play
      when:
        - elk_package_state | default('present') == 'absent'

  post_tasks:
    - name: Drop packetbeat conf file
      template:
        src: templates/packetbeat.yml.j2
        dest: /etc/packetbeat/packetbeat.yml

    - name: Enable and restart packetbeat
      systemd:
        name: "packetbeat"
        enabled: true
        state: restarted

  tags:
    - beat-install

- import_playbook: setupPacketbeat.yml
