---
- name: Install Heartbeat
  hosts: utility_all
  become: true
  vars:
    haproxy_ssl: false

  vars_files:
    - vars/variables.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  pre_tasks:
    - include_tasks: common_task_data_node_hosts.yml

  tasks:
    - include_tasks: common_task_install_elk_repo.yml

    - name: Ensure heartbeat is installed
      apt:
        name: "heartbeat-elastic"
        state: "{{ elk_package_state | default('present') }}"
        update_cache: true
      register: _apt_task
      until: _apt_task is success
      retries: 3
      delay: 2
      tags:
        - package_install

    - name: exit playbook after uninstall
      meta: end_play
      when:
        - elk_package_state | default('present') == 'absent'

  post_tasks:
    - name: Drop heartbeat conf file
      template:
        src: templates/heartbeat.yml.j2
        dest: /etc/heartbeat/heartbeat.yml

    - name: Enable and restart heartbeat
      systemd:
        name: "heartbeat-elastic"
        enabled: true
        state: restarted


- name: Load Heartbeat Dashboards
  hosts: utility_all[0]
  become: true
  vars_files:
    - vars/variables.yml
  tasks:
    - name: Load templates
      shell: >-
        heartbeat setup
        {{ item }}
        -E 'output.logstash.enabled=false'
        -E 'output.elasticsearch.hosts={{ coordination_nodes | to_json }}'
        -e -v
      with_items:
        - "--template"
        - "--dashboards"
      register: templates
      until: templates is success
      retries: 3
      delay: 2
  tags:
    - beat-setup
