---

- name: Load apm-server Dashboards
  hosts: apm-server[0]
  gather_facts: false
  vars_files:
    - vars/variables.yml

  pre_tasks:
    - include_tasks: common_task_data_node_hosts.yml
      tags:
        - always

  tasks:
    - name: Load templates
      shell: >-
        apm-server setup
        {{ item }}
        -E 'apm-server.host=localhost:8200'
        -E 'output.elasticsearch.hosts={{ coordination_nodes | to_json }}'
        -e -v
      with_items:
        - "--template"
        - "--dashboards"
      register: templates
      until: templates is success
      retries: 5
      delay: 5

  tags:
    - beat-setup
