---
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Adds option to set the UID/GID of a given service user.
# service_group_gid: 5000
# service_owner_uid: 5000

# Option to define third memory
q_mem: "{{ (ansible_memtotal_mb | int) // 3 }}"

# Option to define half memory
h_mem: "{{ (ansible_memtotal_mb | int) // 2 }}"

#define this in host/group vars as needed to mount remote filesystems
#set the client address as appropriate, eth1 assumes osa container mgmt network
#mountpoints and server paths are just examples
#elastic_shared_fs_repos:
#  - fstype: nfs4
#    src: "<nfs-server-ip>:/esbackup"
#    opts: clientaddr="{{ ansible_eth1['ipv4']['address'] }}"
#    path: "/elastic-backup"
#    state: mounted

# EXPERIMENTAL - When the heap size for a given elastic node is graeter than
#                4GiB the G1 garbage collector can be enabled. This is an
#                experimental feature and may be removed later.
elastic_g1gc_enabled: false
