---
- name: Enable and start the service
  systemd:
    name: osqueryd
    enabled: true
    state: restarted
  listen: restart osquery

- name: Enable and start the service
  systemd:
    name: rsyslog
    enabled: true
    state: restarted
  listen: restart rsyslog
