---
- name: Install Kolide Fleet
  hosts: "fleet"
  become: true

  vars_files:
    - vars/variables.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  gather_facts: "{{ osa_gather_facts | default(True) }}"

  roles:
    - role: fleet
