---
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

default_interface: "{{ default_network | default('eth0') }}"
default_vm_image: "{{ default_image | default('ubuntu-16.04-amd64') }}"
default_vm_storage: "{{ vm_disk_size | default(92160) }}"

default_os_families:
  ubuntu-16.04-amd64: debian
  ubuntu-14.04-amd64: debian

default_ubuntu_mirror_proxy: 'http://10.0.2.1:3142/'
default_ubuntu_mirror_hostname: archive.ubuntu.com
default_ubuntu_mirror_directory: /ubuntu

 # IP address, or domain name of the TFTP server
tftp_server: "{{ ansible_host }}"
# tftp_ssh_key: ''  # user defined ssh key, used to access the host
tftp_port: 69

# Default ISO images
images:
  ubuntu-16.04-amd64:
    image_type: debian
    image_iso_url: "http://releases.ubuntu.com/16.04.2/ubuntu-16.04.2-server-amd64.iso"
    image_name: "ubuntu-16.04.2-server-amd64.iso"
    image_short_name: "ubuntu-16.04.2-server-amd64"
    image_default_boot: "ubuntu-16.04.2-server-amd64/amd64/boot-screens/menu.cfg"
    image_kernel_options: "biosdevname=0 net.ifnames=0 auto=true priority=critical vga=789"
    image_kernel: "ubuntu-16.04.2-server-amd64/amd64/linux"
    image_initrd: "ubuntu-16.04.2-server-amd64/amd64/initrd.gz"
    image_netboot: "ubuntu-16.04.2-server-amd64/install/netboot/ubuntu-installer"
    image_preseeds:
      mnaio:
        url: "tftp://{{ tftp_server }}/preseed/mnaio.preseed"
        template_name: "mnaio.preseed"
      vm:
        url: "tftp://{{ tftp_server }}/preseed/vm.preseed"
        template_name: "vm.preseed"
  ubuntu-14.04-amd64:
    image_type: debian
    image_iso_url: "http://releases.ubuntu.com/14.04.5/ubuntu-14.04.5-server-amd64.iso"
    image_name: "ubuntu-14.04.5-server-amd64.iso"
    image_short_name: "ubuntu-14.04.5-server-amd64"
    image_default_boot: "ubuntu-14.04.5-server-amd64/amd64/boot-screens/menu.cfg"
    image_kernel_options: "biosdevname=0 net.ifnames=0 auto=true priority=critical vga=789"
    image_kernel: "ubuntu-14.04.5-server-amd64/amd64/linux"
    image_initrd: "ubuntu-14.04.5-server-amd64/amd64/initrd.gz"
    image_netboot: "ubuntu-14.04.5-server-amd64/install/netboot/ubuntu-installer"
    image_preseeds:
      mnaio:
        url: "tftp://{{ tftp_server }}/preseed/mnaio.preseed"
        template_name: "mnaio.preseed"
      vm:
        url: "tftp://{{ tftp_server }}/preseed/vm.preseed"
        template_name: "vm.preseed"
